services:
  llm_dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - huggingface_cache:/app/.cache/huggingface
    environment:
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
    deploy:
      resources:
        limits:
          memory: 8G
    ports:
      - "8888:8888"  

volumes:
  huggingface_cache: