version: '3.8'

services:
  ai_dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - huggingface_cache:/app/.cache/huggingface
    environment:
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8888:8888"  # For Jupyter Notebook if needed
    command: python3

volumes:
  huggingface_cache: