services:
  llm_dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - huggingface_cache:/app/.cache/huggingface
    environment:
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
      # Add environment variables from .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # - OTHER_API_KEY=${OTHER_API_KEY}
    env_file:
      - .env

volumes:
  huggingface_cache: